databases:
  - name: airmartin
    plan: free
    postgresMajorVersion: 14
services:
  - type: web
    name: airmartin
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airmartin_dap6
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false