databases:
  - name: airmartin
   ipAllowList: []
   plan: free

services:
  - type: web
    name: airmartin
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airmartin
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    